//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakipOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_departmanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_departmanlar()
        {
            this.tbl_personeller = new HashSet<tbl_personeller>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
        public string aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_personeller> tbl_personeller { get; set; }
    }
}
